# Generated by Django 6.0.2 on 2026-03-01 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary_range', models.CharField(blank=True, max_length=255)),
                ('positions_filled', models.IntegerField(default=0)),
                ('positions_total', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('applied_date', models.CharField(max_length=100)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('grade', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Rejected', 'Rejected')], max_length=20)),
                ('verified_grade', models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Rejected', 'Rejected')], max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='application.job')),
            ],
        ),
    ]
